#!/bin/bash

#define pd if not defined
type foo >/dev/null 2>&1 || { alias pd='/usr/lib/pd-extended/bin/pd'; }
sudo modprobe snd-bcm2835 
sudo amixer cset numid=3 1
pd -r 22050 -audiobuf 75 -alsa -noadc -nomidi -nogui -send 'pd dsp 1' -rt pd_patches/poly_simp.pd&
sleep 3
python SynthController.py